fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    multi_validatre_re: 'git://github.com/nrvale0/puppet-multi_validate_re.git'
    staging: 'git://github.com/nanliu/puppet-staging'
    dirtree: 'git://github.com/AlexCline/puppet-dirtree'
  symlinks:
    packer: "#{source_dir}"
